/* eslint-disable react/no-unescaped-entities */
import { Box, Container, Divider, Grid, Icon, Typography } from "@mui/material";
import React from "react";
import image2 from "public/assets/image2.jpg";
import image1 from "public/assets/image1.jpg";
import VerticalTimeline from "components/VerticalTimeline";
import BasicCard from "components/Common/BasicCard";
import LinkedinIcon from "components/Icons/LinkedinIcon";
import Banner from "components/Sections/Home/Banner";
import Experience from "components/Sections/Home/Experience";

import Education from "components/Sections/Home/Education";
import WhatIdo from "components/Sections/Home/WhatIdo";
import CoreSkills from "components/Sections/Home/CoreSkills";
import HowIdo from "components/Sections/Home/HowIdo";
import Industries from "components/Sections/Home/Industries";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "components/Sections/Footer";
import AppHeader from "components/Sections/AppHeader";
import PrimaryButton from "components/Common/Button/PrimaryButton";
import FeaturedWorkHome from "components/Sections/Home/FeaturedWorkHome";
import WhatOtherSaying from "components/Sections/Home/WhatOtherSaying";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box>
				<Box>
					<Container maxWidth="lg">
						<AppHeader />
						</Container>
						<Container maxWidth="lg" sx={{marginTop:"200px"}}>
						<Banner />

						<PrimaryButton
							sx={{
								marginX: "40%",
								marginTop: "30px",
								height: "55px",
								paddingLeft:"24px",
								fontSize: "18px",
								border: "1px solid #635bff",
								// backgroundColor: "black",
								// fontFamily:" none",
								transition: "all 0.3s ease-in-out",
								fontFamily: "satoshi, sans-serif !important",
								"&:hover": {
									backgroundColor: "white !important",
									border: "1px solid #635bff",
									color:"#635bff",
									transition: "all 0.3s ease-in-out",
									boxShadow: "none",

								},
							}}
							onClick={() => {
								window.location.href = "/about";
							}}
						>
							Know More
						</PrimaryButton>
					</Container>

					<Experience />

			
					<Container maxWidth="lg">
						<FeaturedWorkHome/>
						<PrimaryButton
							sx={{
								marginX: "40%",
								marginTop: "30px",
								height: "54px",
								fontSize: "18px",
								backgroundColor: "black",
								border: "1px solid #635bff",
								transition: "all 0.3s ease-in-out",
								fontFamily: "satoshi, sans-serif !important",
								"&:hover": {
									backgroundColor: "white !important",
									border: "1px solid #635bff",
									color:"#635bff",
									transition: "all 0.3s ease-in-out",
									boxShadow: "none",

								},
								
							}}
							onClick={() => {
								window.location.href = "/work";
							}}
						>
							View More
						</PrimaryButton>
					<Industries />
					<WhatOtherSaying/>
						{/* <Typography
							sx={{
								fontSize: "48px",
								fontWeight: "800",
								marginBottom: "16px",
								marginTop: "80px",
							}}
						>
							Where I've worked
						</Typography>
					
						<VerticalTimeline />
						<Education />
						<WhatIdo />

						<CoreSkills />

						<HowIdo /> */}

						
						<Footer />
					</Container>
				</Box>
				{/* <SidePanel /> */}
				{/* <Box sx={{ maxHeight: "100vh", overflowY: "scroll" ,flex:"1"}}> */}
				{/* <Container maxWidth="lg" > */}

				{/* </Container> */}
				{/* </Box> */}
			</Box>
		</div>
	);
}
